alias help=run-help
alias la='ls -a'
alias lp='ls -lha'
alias disk='df -h'
alias getip='dip +short myip.opendns.com @resolver1.opendns.com'
alias getgeo='curl ipinfo.io'
alias mail=neomutt
alias twitter=oysttyer
alias rss=canto-curses
alias pkglist='pacman -Qqe > pkglist'
alias up='cd ..'
alias rm='rm -r'
alias vol='alsamixer'
alias mkdir='mkdir -p'
alias cp='cp -r'
alias scp='scp -r'
alias pacman='sudo pacman'
alias systemctl='sudo systemctl'
alias :q="sudo systemctl poweroff"
